// Code generated by hertz generator.

package main

import (
	"context"
	"log"
	"os"
	"strings"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	"thinkbank/backend/biz/dal/minio"
	"thinkbank/backend/biz/dal/postgres"
	"thinkbank/backend/biz/dal/redis"
)

func init() {
	// Initialize database connections
	if err := postgres.Init(nil); err != nil {
		log.Fatalf("Failed to initialize PostgreSQL: %v", err)
	}

	// Initialize Redis
	if err := redis.Init(nil); err != nil {
		log.Fatalf("Failed to initialize Redis: %v", err)
	}

	// Initialize MinIO
	if err := minio.Init(nil); err != nil {
		log.Fatalf("Failed to initialize MinIO: %v", err)
	}

	log.Println("All services initialized successfully")
}

func main() {
	// Get port from environment
	port := os.Getenv("BACKEND_PORT")
	if port == "" {
		port = "8080"
	}

	h := server.Default(
		server.WithHostPorts("0.0.0.0:" + port),
	)

	allowedOrigins := parseAllowedOrigins(
		getEnv("CORS_ALLOWED_ORIGINS", "http://localhost:5173,http://127.0.0.1:5173"),
	)
	allowAllOrigins := len(allowedOrigins) == 1 && allowedOrigins["*"]

	// Enable CORS with environment-controlled allow list.
	h.Use(func(ctx context.Context, c *app.RequestContext) {
		c.Header("Access-Control-Allow-Methods", "GET,POST,PUT,PATCH,DELETE,OPTIONS")
		c.Header("Access-Control-Allow-Headers", "Content-Type,Authorization,Accept,Origin,X-Requested-With")
		c.Header("Access-Control-Expose-Headers", "Content-Length,Content-Type")
		c.Header("Access-Control-Max-Age", "86400")

		origin := string(c.GetHeader("Origin"))
		if allowAllOrigins {
			c.Header("Access-Control-Allow-Origin", "*")
		} else if origin != "" && allowedOrigins[origin] {
			c.Header("Access-Control-Allow-Origin", origin)
			c.Header("Vary", "Origin")
		}

		if string(c.Method()) == consts.MethodOptions {
			c.AbortWithStatus(consts.StatusNoContent)
			return
		}

		c.Next(ctx)
	})

	register(h)
	h.Spin()
}

func getEnv(key, fallback string) string {
	value := strings.TrimSpace(os.Getenv(key))
	if value == "" {
		return fallback
	}
	return value
}

func parseAllowedOrigins(raw string) map[string]bool {
	result := make(map[string]bool)
	for _, item := range strings.Split(raw, ",") {
		origin := strings.TrimSpace(item)
		if origin == "" {
			continue
		}
		result[origin] = true
	}

	if len(result) == 0 {
		result["http://localhost:5173"] = true
		result["http://127.0.0.1:5173"] = true
	}
	return result
}
