// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "thinkbank/backend/biz/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// API v1 routes
	v1 := r.Group("/api/v1")

	// Asset routes
	assets := v1.Group("/assets")
	{
		assets.POST("/upload", handler.Upload)
		assets.GET("", handler.ListAssets)
		assets.GET("/:id", handler.GetAsset)
		assets.DELETE("/:id", handler.DeleteAsset)
	}

	// AI routes
	ai := v1.Group("/ai")
	{
		ai.GET("/health", handler.AIHealth)
	}

	// RAG routes
	v1.GET("/search", handler.Search)
	v1.POST("/chat", handler.Chat)
}
